spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resource-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: resource-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

localstack:
  s3:
    url: http://localhost:4566
    region: us-east-1
    accessKey: test
    secretKey: test

storage-service:
  baseUrl: http://localhost:8087
  storagesUrl: ${storage-service.baseUrl}/storages
  stub-buckets-map:
    STAGING: resource-bucket-staging
    PERMANENT: resource-bucket-permanent

resilience4j:
  circuitbreaker:
    instances:
      storageServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"