spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: resource-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

localstack:
  s3:
    url: ${LOCAL_STACK_S3_URL}
    region: ${LOCAL_STACK_S3_DEFAULT_REGION}
    accessKey: ${LOCAL_STACK_AWS_ACCESS_KEY_ID}
    secretKey: ${LOCAL_STACK_AWS_SECRET_ACCESS_KEY}

storage-service:
  baseUrl: http://gateway/storage-service
  storagesUrl: ${storage-service.baseUrl}/storages
  stub-buckets-map:
    STAGING: resource-bucket-staging
    PERMANENT: resource-bucket-permanent

resilience4j:
  circuitbreaker:
    instances:
      storageServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
