spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/song-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: song-service

server:
  port: 8081

