spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/storage-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: storage-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8087